	subttl	File: CDEF.MAC


; ----------------------------------------------------------------------
;
; This file contains the common global defs for all Cbios.MAC modules.
;
; ---------------------------------------------------------------------- 

		.tfcond		; Don't write out false if's
				;
;		page	47	; Make a PRN file suitable for the OKI1 printer
		page	68	; Make a PRN file suitable for Microline printer
				;
no		equ	0	;
yes		equ	not no	;
				;
fb$ena		equ	no	; Allow fore/background with CTRL-T/U/V
LS$ena		equ	no	; No LineSelector in MY bios.
decenttab	equ	yes	;

kbdsize		equ	32	; 32 char kbd buffer
siosize		equ	256	; 128 char sio buffer, gives 0.5 sec buffer
				; Important at CR/LF's

crt26		equ	yes	; If defined it will set up the screen i/o
				; correctly.

SysReqkey	equ	8ch	; The CLEAR key is the SystemRequestKey.

;------------------------------- Size of drive A: and B:  (8")

disk8sect	equ	74	; Use this number of tracks (normal 60)
				; 2 tracks are reserved, and #77 is for PARKING
d8blocksize	equ	2	; 8" uses 2 kb blocks

disk8size	equ	disk8sect* 15/d8blocksize  	

				; 15 = 120 sectors/8 sectors pr kb
UseHD		equ	no	; Do not include HardDisk routines 910404
UseClock	equ	yes	; Include Clockroutines            910420

lda0		macro		; ld a,0 -- Optimization 	   930424
		ld	a,0
		endm

iso8859		equ	yes	; Support ISO-8859-1 instead of RC for output

usephase	equ	no	; For link = no, for l80 = yes. 


; *** END OF CDEF.MAC ***
